apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: livenessdemo
spec:
  containers:
  - name: busyboxcontainer
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5


#command executed while probing is cat /tmp/healthy , if it's successful (returns zero), container is healthy otherwise killed and restarted.
