apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: springpod
      labels:
        app: spring
    spec:
      containers:
      - image: anjurose/chefapp
        name: springpetclinic
    # nodeSelector:
    #   app: node
---
apiVersion: v1
kind: Service
metadata:
  name: pet-service
spec:
  type: NodePort
  selector:
    app: spring
  ports:
  - port: 80
    targetPort: 8080
    
    #kubectl get nodes --show-labels
   #kubectl label nodes minikube app=spring
   
  #kubectl describe nodes minikube
   
#kubectl describe nodes -l app=spring
  
# vi nodeselection.yml 
   # kubectl apply -f nodeselection.yml
  # kubectl get pods
   # vi nodeselection.yml 
# kubectl get pods
# kubectl apply -f nodeselection.yml
# kubectl get pods
# kubectl describe pod petclinic-74678dbd48-kp8jf
