---
apiVersion: v1
kind: Pod
metadata:
  name: springapp 
spec:
  containers:
  - name: app
    image: anjurose/chefapp 
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
