apiVersion: apps/v1
kind: Deployment 
metadata:
  name: petclinicresourcedemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: springpod
      labels:       
        app: spring              
    spec:
      containers:
      - image: anjurose/chefapp      
        name: springpetclinic
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 
---                                
apiVersion: v1
kind: Service
metadata:
  name: pet-service
spec:
  type: NodePort 
  selector:                        
    app: spring                
  ports:
  - port: 80
    targetPort: 8080
