apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: tomcat
  labels:
    app: tomcat
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
      tier: backend
  template:
    metadata:
      labels:
        app: tomcat
        tier: backend
    spec:
      containers:
      - name: tomcatimage
        image: tomcat:8.0
        ports:
        - containerPort: 8080 
        
---                                
apiVersion: v1
kind: Service
metadata:
  name: tomcatservice
spec:
  type: NodePort 
  selector:                        
    app: tomcat                
  ports:
  - port: 8080
    targetPort: 8080
