apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: Tomcat
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: Tomcat
        tier: Backend
    spec:
      containers:
      - name: Tomcatimage:
        image: tomcat: 8.0
        ports:
        - containerPort: 7474
        
---                                
apiVersion: v1
kind: Service
metadata:
  name: tomcatservice
spec:
  type: NodePort 
  selector:                        
    app: Tomcat                
  ports:
  - port: 7474
    targetPort: 7474        
        
