apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
   - http:
      paths: 
      - path: /first
        backend:
          serviceName: hello-kubernetes-first
          servicePort: 80
      - path: /second
        backend:
          serviceName: hello-kubernetes-second
          servicePort: 80
