apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kubiastable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia2
  template:
    metadata:
      name: kubia2
      labels:       
        app: kubia2                 
        track: stable
    spec:
      containers:
      - image: luksa/kubia:v2      
        name: nodejs
--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kubiacanary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia2
  template:
    metadata:
      name: kubia2
      labels:       
        app: kubia2                 
        track: canary
    spec:
      containers:
      - image: luksa/kubia:v4      
        name: nodejs  
---                             
apiVersion: v1
kind: Service
metadata:
  name: newkubia
spec:
  type: NodePort 
  selector:                        
    app: kubia2                     
  ports:
  - port: 80
    targetPort: 8080
